# Generated by Django 6.0.2 on 2026-02-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_leson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leson',
            new_name='Lesson',
        ),
    ]
