# Generated by Django 6.0.2 on 2026-02-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='craeted_by',
            new_name='created_by',
        ),
    ]
