# Generated by Django 6.0.2 on 2026-02-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_category_options_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
