# Generated by Django 6.0.2 on 2026-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='opt4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
