# Generated by Django 6.0.2 on 2026-02-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_quiz_opt4_quiz_opt5'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'Article'), ('quiz', 'Quiz'), ('video', 'Video')], default='article', max_length=20),
        ),
    ]
